version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    groups:
      test-dependencies:
        patterns:
          - NUnit*
          - "*Test*"
      modularpipelines-dependencies:
        patterns:
          - "*ModularPipeline*"
    ignore:
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
